//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTechNote
    {
        public int TechNotesID { get; set; }
        public int TechID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string TechNote { get; set; }
        public System.DateTime TechNoteDate { get; set; }
    
        public virtual TSTTicket TSTTicket { get; set; }
    }
}
